remote_theme: "mmistakes/so-simple-theme@3.2.0"
title:        "Počítače do škol"
description: "Stránky iniciativy Počítače do škol"
skin:         "/assets/css/skins/light.css"
google_analytics: UA-169225713-1
